from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from functools import lru_cache


@dataclass(frozen=True, slots=True)
class VocabularyEntry:
    word: str
    part_of_speech: str
    definition: str


# Original, concise definitions written for this project. The collection favors
# words that are useful in work, study, relationships, and everyday decisions.
VOCABULARY: tuple[VocabularyEntry, ...] = (
    VocabularyEntry("abate", "verb", "to become less intense or widespread"),
    VocabularyEntry("aberration", "noun", "a departure from what is normal or expected"),
    VocabularyEntry("abridge", "verb", "to shorten something without losing its central meaning"),
    VocabularyEntry("abstain", "verb", "to deliberately choose not to do or consume something"),
    VocabularyEntry("acclaim", "noun", "enthusiastic public praise or approval"),
    VocabularyEntry("accolade", "noun", "an award or expression of recognition"),
    VocabularyEntry("accommodate", "verb", "to make room for a need, person, or circumstance"),
    VocabularyEntry("accord", "noun", "an agreement or state of harmony"),
    VocabularyEntry("accountable", "adjective", "responsible for actions and answerable for their results"),
    VocabularyEntry("accrue", "verb", "to accumulate gradually over time"),
    VocabularyEntry("acumen", "noun", "the ability to make quick, sound judgments"),
    VocabularyEntry("adamant", "adjective", "unwilling to change a firm decision or position"),
    VocabularyEntry("adept", "adjective", "highly skilled at a particular activity"),
    VocabularyEntry("adhere", "verb", "to follow a rule or remain committed to a principle"),
    VocabularyEntry("adjacent", "adjective", "next to or very near something else"),
    VocabularyEntry("advocate", "verb", "to publicly support a cause, policy, or person"),
    VocabularyEntry("aesthetic", "adjective", "concerned with beauty, taste, or visual appeal"),
    VocabularyEntry("affinity", "noun", "a natural connection, attraction, or shared understanding"),
    VocabularyEntry("affirm", "verb", "to state or confirm something with confidence"),
    VocabularyEntry("aggregate", "verb", "to collect separate items into a combined whole"),
    VocabularyEntry("agile", "adjective", "able to move, think, or adapt quickly"),
    VocabularyEntry("alleviate", "verb", "to make pain, difficulty, or pressure less severe"),
    VocabularyEntry("allocate", "verb", "to assign resources for a particular purpose"),
    VocabularyEntry("allude", "verb", "to refer to something indirectly"),
    VocabularyEntry("altruistic", "adjective", "motivated by concern for other people's well-being"),
    VocabularyEntry("ambiguous", "adjective", "open to more than one reasonable interpretation"),
    VocabularyEntry("amenable", "adjective", "open and responsive to a suggestion or change"),
    VocabularyEntry("amplify", "verb", "to increase the strength, reach, or importance of something"),
    VocabularyEntry("analogous", "adjective", "similar in a way that makes comparison useful"),
    VocabularyEntry("anecdotal", "adjective", "based on personal stories rather than systematic evidence"),
    VocabularyEntry("anomaly", "noun", "something that differs noticeably from the usual pattern"),
    VocabularyEntry("anticipate", "verb", "to expect and prepare for a future event"),
    VocabularyEntry("apathy", "noun", "a lack of interest, concern, or motivation"),
    VocabularyEntry("appease", "verb", "to calm or satisfy someone by meeting a demand"),
    VocabularyEntry("applicable", "adjective", "relevant and suitable for a particular situation"),
    VocabularyEntry("apprehensive", "adjective", "anxious or uneasy about what may happen"),
    VocabularyEntry("arbitrary", "adjective", "based on personal choice rather than a clear reason"),
    VocabularyEntry("articulate", "verb", "to express an idea clearly and effectively"),
    VocabularyEntry("ascertain", "verb", "to discover something with reasonable certainty"),
    VocabularyEntry("aspiration", "noun", "a strong hope or ambition for the future"),
    VocabularyEntry("assertive", "adjective", "confident and direct while respecting other people"),
    VocabularyEntry("assess", "verb", "to evaluate the quality, importance, or extent of something"),
    VocabularyEntry("astute", "adjective", "quick to notice and understand important details"),
    VocabularyEntry("attainable", "adjective", "realistically possible to achieve"),
    VocabularyEntry("attribute", "verb", "to regard something as caused by a particular source"),
    VocabularyEntry("augment", "verb", "to increase something by adding to it"),
    VocabularyEntry("authentic", "adjective", "genuine and consistent with one's actual values or origin"),
    VocabularyEntry("autonomous", "adjective", "able to make decisions and act independently"),
    VocabularyEntry("avert", "verb", "to prevent an unwanted event or turn attention away"),
    VocabularyEntry("benevolent", "adjective", "kind and motivated by a desire to help"),
    VocabularyEntry("bias", "noun", "a tendency that unfairly influences judgment"),
    VocabularyEntry("bolster", "verb", "to support or strengthen something"),
    VocabularyEntry("brevity", "noun", "the effective use of few words or little time"),
    VocabularyEntry("candid", "adjective", "honest and direct, even when the truth is difficult"),
    VocabularyEntry("capitalize", "verb", "to use a situation to gain an advantage"),
    VocabularyEntry("catalyst", "noun", "a person or event that speeds up significant change"),
    VocabularyEntry("categorical", "adjective", "stated clearly and without exceptions or conditions"),
    VocabularyEntry("cautious", "adjective", "careful to avoid unnecessary risk or error"),
    VocabularyEntry("cease", "verb", "to bring an activity or process to an end"),
    VocabularyEntry("coherent", "adjective", "logical, consistent, and easy to understand"),
    VocabularyEntry("collaborate", "verb", "to work with others toward a shared result"),
    VocabularyEntry("compelling", "adjective", "strongly persuasive or capable of holding attention"),
    VocabularyEntry("compensate", "verb", "to make up for a loss, effort, or disadvantage"),
    VocabularyEntry("complacent", "adjective", "too satisfied to notice danger or room for improvement"),
    VocabularyEntry("complement", "verb", "to add something that improves or completes another thing"),
    VocabularyEntry("comprehensive", "adjective", "covering nearly every important part of a subject"),
    VocabularyEntry("concede", "verb", "to admit that a point is true or valid"),
    VocabularyEntry("concise", "adjective", "clear and complete without unnecessary words"),
    VocabularyEntry("concurrent", "adjective", "happening or operating at the same time"),
    VocabularyEntry("conducive", "adjective", "creating conditions that make an outcome more likely"),
    VocabularyEntry("confer", "verb", "to discuss a matter before reaching a decision"),
    VocabularyEntry("consensus", "noun", "general agreement among members of a group"),
    VocabularyEntry("consequential", "adjective", "important because of its effects or results"),
    VocabularyEntry("consolidate", "verb", "to combine parts into a stronger or simpler whole"),
    VocabularyEntry("constrain", "verb", "to limit choices, movement, or development"),
    VocabularyEntry("constructive", "adjective", "intended to improve a situation or help someone progress"),
    VocabularyEntry("contemplate", "verb", "to think carefully about something for an extended time"),
    VocabularyEntry("contend", "verb", "to argue that a claim or position is true"),
    VocabularyEntry("contingency", "noun", "a possible event that requires a backup plan"),
    VocabularyEntry("contrary", "adjective", "opposite in nature, direction, or meaning"),
    VocabularyEntry("conventional", "adjective", "following widely accepted practices or expectations"),
    VocabularyEntry("converge", "verb", "to move toward the same point, result, or opinion"),
    VocabularyEntry("convey", "verb", "to communicate an idea, feeling, or piece of information"),
    VocabularyEntry("cordial", "adjective", "warm, polite, and friendly without being overly familiar"),
    VocabularyEntry("corroborate", "verb", "to support a statement with additional evidence"),
    VocabularyEntry("credible", "adjective", "believable because it is trustworthy and well supported"),
    VocabularyEntry("criterion", "noun", "a standard used to judge or decide something"),
    VocabularyEntry("crucial", "adjective", "extremely important to the success of an outcome"),
    VocabularyEntry("cultivate", "verb", "to deliberately develop a skill, quality, or relationship"),
    VocabularyEntry("cumulative", "adjective", "increasing through a series of additions over time"),
    VocabularyEntry("curb", "verb", "to control or reduce unwanted behavior or growth"),
    VocabularyEntry("daunting", "adjective", "seeming difficult enough to cause hesitation"),
    VocabularyEntry("debrief", "verb", "to review an experience and extract useful lessons"),
    VocabularyEntry("decipher", "verb", "to work out the meaning of something unclear"),
    VocabularyEntry("decisive", "adjective", "able to make choices promptly and confidently"),
    VocabularyEntry("decline", "verb", "to politely refuse or to become smaller or weaker"),
    VocabularyEntry("deduce", "verb", "to reach a conclusion through evidence and reasoning"),
    VocabularyEntry("defer", "verb", "to postpone an action or yield to another person's judgment"),
    VocabularyEntry("deliberate", "adjective", "done consciously and with careful consideration"),
    VocabularyEntry("delineate", "verb", "to describe the boundaries or details of something precisely"),
    VocabularyEntry("denote", "verb", "to indicate or directly mean something"),
    VocabularyEntry("depict", "verb", "to represent something in words or images"),
    VocabularyEntry("derive", "verb", "to obtain something from a particular source"),
    VocabularyEntry("designate", "verb", "to officially assign a name, role, or purpose"),
    VocabularyEntry("deteriorate", "verb", "to become progressively worse in quality or condition"),
    VocabularyEntry("detrimental", "adjective", "causing harm or reducing the chance of success"),
    VocabularyEntry("deviate", "verb", "to depart from an established route, rule, or pattern"),
    VocabularyEntry("diligent", "adjective", "careful and persistent in completing work well"),
    VocabularyEntry("discern", "verb", "to notice or understand something that is not obvious"),
    VocabularyEntry("disclose", "verb", "to make previously private information known"),
    VocabularyEntry("discreet", "adjective", "careful not to attract attention or reveal private information"),
    VocabularyEntry("dissonance", "noun", "tension caused by conflicting ideas, beliefs, or sounds"),
    VocabularyEntry("distinct", "adjective", "clearly different or separately recognizable"),
    VocabularyEntry("distort", "verb", "to alter something so it becomes misleading or inaccurate"),
    VocabularyEntry("diverge", "verb", "to move apart or develop in different directions"),
    VocabularyEntry("diverse", "adjective", "including people or things with meaningful differences"),
    VocabularyEntry("divulge", "verb", "to reveal information that was private or secret"),
    VocabularyEntry("dormant", "adjective", "temporarily inactive but capable of becoming active"),
    VocabularyEntry("dubious", "adjective", "uncertain, doubtful, or not fully trustworthy"),
    VocabularyEntry("dynamic", "adjective", "characterized by energy, change, or active interaction"),
    VocabularyEntry("eclectic", "adjective", "drawn from a wide variety of styles or sources"),
    VocabularyEntry("elaborate", "verb", "to add details that make an idea clearer"),
    VocabularyEntry("elicit", "verb", "to draw out a response, reaction, or piece of information"),
    VocabularyEntry("eloquent", "adjective", "fluent and persuasive in speaking or writing"),
    VocabularyEntry("embody", "verb", "to clearly represent or express an idea or quality"),
    VocabularyEntry("empirical", "adjective", "based on observation or experiment rather than theory alone"),
    VocabularyEntry("emulate", "verb", "to match or surpass a good example through imitation"),
    VocabularyEntry("enable", "verb", "to give someone or something the means to act"),
    VocabularyEntry("encompass", "verb", "to include a wide range of things within one whole"),
    VocabularyEntry("endorse", "verb", "to publicly approve or recommend something"),
    VocabularyEntry("enhance", "verb", "to improve the quality, value, or effectiveness of something"),
    VocabularyEntry("entail", "verb", "to involve something as a necessary consequence"),
    VocabularyEntry("envision", "verb", "to imagine a future possibility in a detailed way"),
    VocabularyEntry("equitable", "adjective", "fair while accounting for different needs and circumstances"),
    VocabularyEntry("eradicate", "verb", "to eliminate something harmful or unwanted completely"),
    VocabularyEntry("erratic", "adjective", "unpredictable and lacking a steady pattern"),
    VocabularyEntry("escalate", "verb", "to increase quickly in seriousness, size, or intensity"),
    VocabularyEntry("essence", "noun", "the central quality or most important nature of something"),
    VocabularyEntry("ethical", "adjective", "consistent with accepted principles of right conduct"),
    VocabularyEntry("evaluate", "verb", "to judge something using evidence and stated standards"),
    VocabularyEntry("evident", "adjective", "clearly seen or understood from available information"),
    VocabularyEntry("evoke", "verb", "to bring a feeling, memory, or image to mind"),
    VocabularyEntry("exacerbate", "verb", "to make a problem or difficult situation worse"),
    VocabularyEntry("exemplary", "adjective", "excellent enough to serve as a model for others"),
    VocabularyEntry("exhaustive", "adjective", "thorough enough to include every relevant possibility"),
    VocabularyEntry("explicit", "adjective", "stated fully and clearly, leaving little room for doubt"),
    VocabularyEntry("facilitate", "verb", "to make an action or process easier"),
    VocabularyEntry("feasible", "adjective", "possible and practical with the available resources"),
    VocabularyEntry("finite", "adjective", "having a definite limit or end"),
    VocabularyEntry("fluctuate", "verb", "to rise and fall irregularly over time"),
    VocabularyEntry("formulate", "verb", "to develop an idea or plan in a systematic way"),
    VocabularyEntry("foster", "verb", "to encourage the development of something positive"),
    VocabularyEntry("forthcoming", "adjective", "willing to share information openly and promptly"),
    VocabularyEntry("fortify", "verb", "to strengthen something against difficulty or attack"),
    VocabularyEntry("frugal", "adjective", "careful to avoid waste when using money or resources"),
    VocabularyEntry("futile", "adjective", "incapable of producing a useful result"),
    VocabularyEntry("gauge", "verb", "to estimate or measure the amount, level, or response"),
    VocabularyEntry("genuine", "adjective", "sincere, authentic, and not false or artificial"),
    VocabularyEntry("gradual", "adjective", "happening slowly through small stages"),
    VocabularyEntry("granular", "adjective", "presented at a fine level of detail"),
    VocabularyEntry("holistic", "adjective", "considering a complete system rather than isolated parts"),
    VocabularyEntry("hypothetical", "adjective", "imagined for discussion rather than established as fact"),
    VocabularyEntry("impartial", "adjective", "fair and not favoring one side over another"),
    VocabularyEntry("implement", "verb", "to put a plan or decision into practical effect"),
    VocabularyEntry("implicit", "adjective", "suggested or understood without being directly stated"),
    VocabularyEntry("incentive", "noun", "something that motivates or rewards a particular action"),
    VocabularyEntry("incisive", "adjective", "clear, direct, and intelligently focused on what matters"),
    VocabularyEntry("inclusive", "adjective", "designed to welcome and involve people with different needs"),
    VocabularyEntry("incumbent", "adjective", "necessary as a duty or responsibility"),
    VocabularyEntry("indifferent", "adjective", "having no particular interest, concern, or preference"),
    VocabularyEntry("indispensable", "adjective", "so useful or important that it cannot be replaced"),
    VocabularyEntry("infer", "verb", "to reach a conclusion from evidence rather than direct statements"),
    VocabularyEntry("inhibit", "verb", "to restrain, slow, or prevent an action or process"),
    VocabularyEntry("innovative", "adjective", "introducing a genuinely useful new method or idea"),
    VocabularyEntry("insightful", "adjective", "showing a deep and accurate understanding"),
    VocabularyEntry("integral", "adjective", "essential to the completeness or operation of something"),
    VocabularyEntry("integrity", "noun", "honesty and consistency between values and actions"),
    VocabularyEntry("intermittent", "adjective", "stopping and starting at irregular intervals"),
    VocabularyEntry("interpret", "verb", "to explain or decide the meaning of something"),
    VocabularyEntry("intrinsic", "adjective", "belonging naturally to the essential character of something"),
    VocabularyEntry("intuitive", "adjective", "easy to understand without detailed instruction"),
    VocabularyEntry("invalidate", "verb", "to show that a claim or result is not sound"),
    VocabularyEntry("invoke", "verb", "to call on a rule, authority, memory, or idea"),
    VocabularyEntry("iterate", "verb", "to repeat a process while improving it each time"),
    VocabularyEntry("judicious", "adjective", "showing careful thought and sound judgment"),
    VocabularyEntry("juxtapose", "verb", "to place things together so their differences become clear"),
    VocabularyEntry("keen", "adjective", "highly perceptive, eager, or strongly developed"),
    VocabularyEntry("latent", "adjective", "present but not yet active or visible"),
    VocabularyEntry("leverage", "verb", "to use a resource or advantage for greater effect"),
    VocabularyEntry("liable", "adjective", "legally responsible or likely to experience something"),
    VocabularyEntry("lucid", "adjective", "expressed clearly and easy to understand"),
    VocabularyEntry("lucrative", "adjective", "producing a significant financial gain"),
    VocabularyEntry("mandate", "noun", "an official requirement or clear authorization to act"),
    VocabularyEntry("marginal", "adjective", "small in importance, amount, or effect"),
    VocabularyEntry("mediate", "verb", "to help opposing sides reach an agreement"),
    VocabularyEntry("meticulous", "adjective", "extremely careful about accuracy and small details"),
    VocabularyEntry("mitigate", "verb", "to reduce the severity or harmful effect of something"),
    VocabularyEntry("mobilize", "verb", "to organize people or resources for action"),
    VocabularyEntry("moderate", "verb", "to make something less extreme or intense"),
    VocabularyEntry("mundane", "adjective", "ordinary and lacking special interest or excitement"),
    VocabularyEntry("mutual", "adjective", "shared, experienced, or given by each side"),
    VocabularyEntry("nuanced", "adjective", "showing subtle distinctions instead of a simple contrast"),
    VocabularyEntry("objective", "adjective", "based on observable facts rather than personal feelings"),
    VocabularyEntry("obsolete", "adjective", "no longer useful because something newer has replaced it"),
    VocabularyEntry("offset", "verb", "to balance the effect of something with an opposing factor"),
    VocabularyEntry("opaque", "adjective", "difficult to understand or impossible to see through"),
    VocabularyEntry("optimal", "adjective", "best or most effective under the circumstances"),
    VocabularyEntry("orchestrate", "verb", "to coordinate many parts so they work together"),
    VocabularyEntry("ostensibly", "adverb", "apparently true, though the reality may differ"),
    VocabularyEntry("outcome", "noun", "the final result of an action or process"),
    VocabularyEntry("overarching", "adjective", "broad enough to include and influence many smaller parts"),
    VocabularyEntry("paradox", "noun", "a situation that seems contradictory but may reveal a truth"),
    VocabularyEntry("paramount", "adjective", "more important than anything else in the situation"),
    VocabularyEntry("parity", "noun", "a state of equality in status, value, or conditions"),
    VocabularyEntry("perceive", "verb", "to notice, understand, or interpret something"),
    VocabularyEntry("peripheral", "adjective", "secondary or located near the outer edge"),
    VocabularyEntry("pervasive", "adjective", "spreading widely throughout an area or group"),
    VocabularyEntry("plausible", "adjective", "reasonable enough to be believed as possible"),
    VocabularyEntry("pragmatic", "adjective", "focused on practical results and what works"),
    VocabularyEntry("precedent", "noun", "an earlier example used to guide a later decision"),
    VocabularyEntry("precise", "adjective", "exact, accurate, and clearly defined"),
    VocabularyEntry("preliminary", "adjective", "done in preparation for a more complete action"),
    VocabularyEntry("premise", "noun", "a statement or idea on which an argument is based"),
    VocabularyEntry("prevalent", "adjective", "common or widespread in a particular place or time"),
    VocabularyEntry("proactive", "adjective", "acting early to influence events instead of merely reacting"),
    VocabularyEntry("proficient", "adjective", "competent and skilled at doing something"),
    VocabularyEntry("profound", "adjective", "having deep meaning, insight, or effect"),
    VocabularyEntry("prohibit", "verb", "to formally forbid an action"),
    VocabularyEntry("prominent", "adjective", "important, noticeable, or widely recognized"),
    VocabularyEntry("prone", "adjective", "likely or naturally inclined to experience something"),
    VocabularyEntry("prospective", "adjective", "expected or likely to happen in the future"),
    VocabularyEntry("prudent", "adjective", "careful and sensible about future consequences"),
    VocabularyEntry("qualitative", "adjective", "concerned with qualities and meanings rather than quantities"),
    VocabularyEntry("quantify", "verb", "to express or measure something as a number"),
    VocabularyEntry("rationale", "noun", "the reasoning that explains a decision or belief"),
    VocabularyEntry("reconcile", "verb", "to restore agreement or make conflicting ideas compatible"),
    VocabularyEntry("refine", "verb", "to improve something through small, careful changes"),
    VocabularyEntry("reinforce", "verb", "to strengthen an idea, behavior, or physical structure"),
    VocabularyEntry("reluctant", "adjective", "unwilling and hesitant to take an action"),
    VocabularyEntry("remediate", "verb", "to correct or reduce a problem or deficiency"),
    VocabularyEntry("resilient", "adjective", "able to recover and adapt after difficulty"),
    VocabularyEntry("resolve", "verb", "to settle a problem or decide firmly on a course"),
    VocabularyEntry("restrain", "verb", "to hold back or keep something under control"),
    VocabularyEntry("retain", "verb", "to continue to have, remember, or employ something"),
    VocabularyEntry("rigorous", "adjective", "extremely thorough, accurate, and demanding"),
    VocabularyEntry("robust", "adjective", "strong and effective across difficult conditions"),
    VocabularyEntry("salient", "adjective", "most noticeable or relevant to the matter at hand"),
    VocabularyEntry("scrutinize", "verb", "to examine something closely for important details"),
    VocabularyEntry("seamless", "adjective", "smooth and continuous, with no obvious interruption"),
    VocabularyEntry("skeptical", "adjective", "not easily convinced without sufficient evidence"),
    VocabularyEntry("solicit", "verb", "to actively ask for information, support, or business"),
    VocabularyEntry("sparse", "adjective", "thinly distributed or present in small amounts"),
    VocabularyEntry("sporadic", "adjective", "occurring occasionally and without a regular pattern"),
    VocabularyEntry("stagnant", "adjective", "showing little movement, growth, or progress"),
    VocabularyEntry("strategic", "adjective", "planned to advance an important long-term objective"),
    VocabularyEntry("streamline", "verb", "to simplify a process by removing unnecessary steps"),
    VocabularyEntry("substantive", "adjective", "meaningful, important, and supported by real content"),
    VocabularyEntry("subtle", "adjective", "delicate or difficult to notice immediately"),
    VocabularyEntry("succinct", "adjective", "briefly and clearly expressed"),
    VocabularyEntry("sufficient", "adjective", "enough to meet a need or requirement"),
    VocabularyEntry("supplement", "verb", "to add something that completes or improves what exists"),
    VocabularyEntry("suppress", "verb", "to prevent an action, feeling, or information from emerging"),
    VocabularyEntry("sustainable", "adjective", "able to continue without exhausting necessary resources"),
    VocabularyEntry("synthesize", "verb", "to combine separate ideas into a coherent whole"),
    VocabularyEntry("tangible", "adjective", "clear and definite enough to be measured or felt"),
    VocabularyEntry("tentative", "adjective", "not yet certain, final, or fully confident"),
    VocabularyEntry("thorough", "adjective", "careful and complete, with no important omissions"),
    VocabularyEntry("threshold", "noun", "the point at which a change or action begins"),
    VocabularyEntry("trajectory", "noun", "the direction in which a situation is developing"),
    VocabularyEntry("transparent", "adjective", "open, understandable, and free from hidden motives"),
    VocabularyEntry("trivial", "adjective", "too minor to deserve much attention"),
    VocabularyEntry("undermine", "verb", "to gradually weaken confidence, authority, or effectiveness"),
    VocabularyEntry("unequivocal", "adjective", "clear and unambiguous, with no room for doubt"),
    VocabularyEntry("unprecedented", "adjective", "never known or experienced before"),
    VocabularyEntry("validate", "verb", "to confirm that something is sound, accurate, or acceptable"),
    VocabularyEntry("viable", "adjective", "capable of working successfully in practice"),
    VocabularyEntry("vigilant", "adjective", "alert and watchful for possible problems"),
    VocabularyEntry("volatile", "adjective", "likely to change suddenly and unpredictably"),
    VocabularyEntry("warrant", "verb", "to justify or make a particular action necessary"),
    VocabularyEntry("yield", "verb", "to produce a result or give way under pressure"),
    VocabularyEntry("adaptable", "adjective", "able to adjust effectively when circumstances change"),
    VocabularyEntry("adversity", "noun", "a difficult condition that tests a person's resilience"),
    VocabularyEntry("amicable", "adjective", "friendly and peaceful despite a disagreement"),
    VocabularyEntry("assiduous", "adjective", "showing persistent care and effort"),
    VocabularyEntry("attentive", "adjective", "carefully noticing and responding to another person's needs"),
    VocabularyEntry("balanced", "adjective", "giving appropriate weight to different needs or viewpoints"),
    VocabularyEntry("circumspect", "adjective", "careful to consider risks before speaking or acting"),
    VocabularyEntry("clarify", "verb", "to make an idea or statement easier to understand"),
    VocabularyEntry("commensurate", "adjective", "matching something else in size, degree, or importance"),
    VocabularyEntry("compassionate", "adjective", "aware of suffering and motivated to help"),
    VocabularyEntry("compatible", "adjective", "able to exist or work together without conflict"),
    VocabularyEntry("conscientious", "adjective", "careful, responsible, and guided by a desire to do right"),
    VocabularyEntry("contextual", "adjective", "understood in relation to surrounding circumstances"),
    VocabularyEntry("conviction", "noun", "a firmly held belief or confident sense of certainty"),
    VocabularyEntry("diplomatic", "adjective", "tactful in handling sensitive people or situations"),
    VocabularyEntry("discerning", "adjective", "showing good judgment about subtle differences in quality"),
    VocabularyEntry("efficient", "adjective", "achieving a result with minimal wasted effort or resources"),
    VocabularyEntry("empathetic", "adjective", "able to understand and share another person's feelings"),
    VocabularyEntry("engender", "verb", "to cause a feeling, condition, or situation to develop"),
    VocabularyEntry("expedite", "verb", "to make a process happen sooner"),
    VocabularyEntry("flexible", "adjective", "willing and able to adjust to changing needs"),
    VocabularyEntry("foresight", "noun", "the ability to anticipate future needs or consequences"),
    VocabularyEntry("forthright", "adjective", "direct and honest in speech or behavior"),
    VocabularyEntry("gratuitous", "adjective", "unnecessary or lacking a reasonable purpose"),
    VocabularyEntry("impeccable", "adjective", "meeting an exceptionally high standard without obvious faults"),
    VocabularyEntry("industrious", "adjective", "consistently hardworking and productive"),
    VocabularyEntry("inquisitive", "adjective", "eager to learn by asking thoughtful questions"),
    VocabularyEntry("intentional", "adjective", "done on purpose and aligned with a chosen aim"),
    VocabularyEntry("measured", "adjective", "calm, deliberate, and carefully controlled"),
    VocabularyEntry("methodical", "adjective", "following an orderly and systematic process"),
    VocabularyEntry("perceptive", "adjective", "quick to notice and understand subtle details"),
    VocabularyEntry("receptive", "adjective", "willing to consider new ideas or feedback"),
    VocabularyEntry("reciprocal", "adjective", "given or felt in return by both sides"),
    VocabularyEntry("resourceful", "adjective", "skilled at finding practical ways through difficulty"),
    VocabularyEntry("tactful", "adjective", "honest while carefully avoiding unnecessary offense"),
    VocabularyEntry("tenacious", "adjective", "persistent and unwilling to abandon a worthwhile goal"),
    VocabularyEntry("versatile", "adjective", "capable of adapting to many different uses or roles"),
    VocabularyEntry("acclimate", "verb", "to adjust gradually to a new environment or situation"),
    VocabularyEntry("acknowledge", "verb", "to recognize the truth, value, or presence of something"),
    VocabularyEntry("actionable", "adjective", "specific and practical enough to guide a next step"),
    VocabularyEntry("apt", "adjective", "especially suitable or appropriate in the circumstances"),
    VocabularyEntry("ardent", "adjective", "showing strong enthusiasm or commitment"),
    VocabularyEntry("audacious", "adjective", "boldly willing to take an unusual risk"),
    VocabularyEntry("beneficial", "adjective", "producing a helpful or favorable result"),
    VocabularyEntry("boundary", "noun", "a limit that protects a space, role, or relationship"),
    VocabularyEntry("calibrate", "verb", "to adjust something carefully for accuracy or effectiveness"),
    VocabularyEntry("capacity", "noun", "the maximum amount that can be held, done, or understood"),
    VocabularyEntry("causal", "adjective", "relating to the connection between a cause and its effect"),
    VocabularyEntry("cohesive", "adjective", "forming a unified and logically connected whole"),
    VocabularyEntry("commend", "verb", "to praise someone or recommend something as worthy"),
    VocabularyEntry("competent", "adjective", "having the skill needed to perform a task successfully"),
    VocabularyEntry("compromise", "noun", "an agreement reached through concessions by each side"),
    VocabularyEntry("conclusive", "adjective", "strong enough to settle a question or uncertainty"),
    VocabularyEntry("conditional", "adjective", "dependent on another event or requirement"),
    VocabularyEntry("consistent", "adjective", "acting or occurring in a stable, dependable pattern"),
    VocabularyEntry("contemporary", "adjective", "belonging to or reflecting the present period"),
    VocabularyEntry("context", "noun", "the surrounding facts that give something its meaning"),
    VocabularyEntry("critique", "noun", "a careful evaluation that identifies strengths and weaknesses"),
    VocabularyEntry("deference", "noun", "respect shown by yielding to another person's judgment"),
    VocabularyEntry("demystify", "verb", "to make a difficult subject easier to understand"),
    VocabularyEntry("dependable", "adjective", "reliable enough to be trusted consistently"),
    VocabularyEntry("diminish", "verb", "to make or become smaller, weaker, or less important"),
    VocabularyEntry("disproportionate", "adjective", "too large or small in relation to something else"),
    VocabularyEntry("disseminate", "verb", "to distribute information widely"),
    VocabularyEntry("efficacy", "noun", "the ability to produce the intended result"),
    VocabularyEntry("emerging", "adjective", "newly developing or becoming more visible"),
    VocabularyEntry("enduring", "adjective", "continuing for a long time despite difficulty"),
    VocabularyEntry("enrich", "verb", "to improve quality by adding value, knowledge, or variety"),
    VocabularyEntry("erroneous", "adjective", "incorrect because of a mistake or false assumption"),
    VocabularyEntry("exceptional", "adjective", "unusually excellent or notably different"),
    VocabularyEntry("extrapolate", "verb", "to estimate beyond known facts using an existing pattern"),
    VocabularyEntry("improvise", "verb", "to create or act using what is immediately available"),
    VocabularyEntry("inadvertent", "adjective", "unintentional and usually caused by lack of attention"),
    VocabularyEntry("inconclusive", "adjective", "not sufficient to produce a firm decision"),
    VocabularyEntry("incremental", "adjective", "advancing through a series of small changes"),
    VocabularyEntry("inevitable", "adjective", "certain to happen or impossible to avoid"),
    VocabularyEntry("informed", "adjective", "based on relevant knowledge and reliable information"),
    VocabularyEntry("inherent", "adjective", "existing as a natural or essential part of something"),
    VocabularyEntry("initiative", "noun", "the ability to act without waiting to be directed"),
    VocabularyEntry("interpersonal", "adjective", "relating to communication and relationships between people"),
    VocabularyEntry("legitimate", "adjective", "lawful, reasonable, or supported by valid grounds"),
    VocabularyEntry("momentum", "noun", "growing progress that makes continued movement easier"),
    VocabularyEntry("neutral", "adjective", "not supporting one side in a disagreement"),
    VocabularyEntry("nominal", "adjective", "very small or existing mainly in name"),
    VocabularyEntry("noteworthy", "adjective", "important or unusual enough to deserve attention"),
    VocabularyEntry("perspective", "noun", "a particular way of understanding a situation"),
    VocabularyEntry("prioritize", "verb", "to arrange tasks or needs by their importance"),
    VocabularyEntry("redundant", "adjective", "unnecessary because it repeats or duplicates something"),
    VocabularyEntry("relevant", "adjective", "closely connected to the matter being considered"),
    VocabularyEntry("reliable", "adjective", "consistently accurate, effective, or trustworthy"),
    VocabularyEntry("retrospective", "adjective", "looking back on past events to understand them"),
    VocabularyEntry("scope", "noun", "the defined range of work, influence, or attention"),
    VocabularyEntry("sensible", "adjective", "showing practical judgment and awareness of consequences"),
    VocabularyEntry("significant", "adjective", "important enough to have a noticeable effect"),
    VocabularyEntry("spontaneous", "adjective", "arising naturally without advance planning"),
    VocabularyEntry("stable", "adjective", "unlikely to change suddenly or fail"),
    VocabularyEntry("tolerance", "noun", "the ability to accept difference, strain, or uncertainty"),
    VocabularyEntry("transient", "adjective", "lasting only for a short time"),
    VocabularyEntry("trustworthy", "adjective", "deserving confidence because of reliable character or behavior"),
    VocabularyEntry("unanimous", "adjective", "fully agreed upon by everyone involved"),
    VocabularyEntry("vulnerable", "adjective", "open to harm, criticism, or emotional exposure"),
)


@lru_cache(maxsize=1)
def _vocabulary_order() -> tuple[int, ...]:
    return tuple(
        sorted(
            range(len(VOCABULARY)),
            key=lambda index: hashlib.sha256(f"inky-arena:vocabulary:{VOCABULARY[index].word}".encode()).digest(),
        )
    )


def entry_for_position(position: int) -> VocabularyEntry:
    if position < 0:
        raise ValueError("vocabulary position must be non-negative")
    offset = position % len(VOCABULARY)
    return VOCABULARY[_vocabulary_order()[offset]]


def _day_and_slot(moment: datetime) -> tuple[date, int]:
    if moment.hour < 6:
        return moment.date() - timedelta(days=1), 3
    if moment.hour < 10:
        return moment.date(), 0
    if moment.hour < 14:
        return moment.date(), 1
    if moment.hour < 18:
        return moment.date(), 2
    return moment.date(), 3


def period_for_datetime(moment: datetime) -> str:
    day, slot = _day_and_slot(moment)
    return f"{day.isoformat()}-{slot}"


def entry_for_datetime(moment: datetime) -> VocabularyEntry:
    day, slot = _day_and_slot(moment)
    return entry_for_position(day.toordinal() * 4 + slot)
